remote_theme: abhinavs/moonwalk

title: "icchou233's blog"
author: I-Chen Chou

navigation:
  - title: Home
    url: /
  - title: Blog
    url: /blog/
  - title: About
    url: /about/

# Enable posts listing on /blog
paginate: 5
paginate_path: "/blog/page:num/"
